# Mathematical Operation on NumPy Array

In [1]:
import numpy as np

In [2]:
arr1=np.arange(1,21)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [3]:
arr1**4

array([     1,     16,     81,    256,    625,   1296,   2401,   4096,
         6561,  10000,  14641,  20736,  28561,  38416,  50625,  65536,
        83521, 104976, 130321, 160000], dtype=int32)

In [4]:
arr1+arr1

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40])

## Mathematical Operation on a Matrix

In [5]:
arr1=arr1.reshape(2,-1)
arr1

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [6]:
arr1**4

array([[     1,     16,     81,    256,    625,   1296,   2401,   4096,
          6561,  10000],
       [ 14641,  20736,  28561,  38416,  50625,  65536,  83521, 104976,
        130321, 160000]], dtype=int32)

In [7]:
arr1*arr1

array([[  1,   4,   9,  16,  25,  36,  49,  64,  81, 100],
       [121, 144, 169, 196, 225, 256, 289, 324, 361, 400]])

In [8]:
arr1.dot(arr1.reshape(-1,2))

array([[ 715,  770],
       [1715, 1870]])