In [1]:
import numpy as np

In [2]:
arr1=np.zeros(5)
print(arr1)

[0. 0. 0. 0. 0.]


In [3]:
arr2=np.ones((2,5))
print(arr2)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [4]:
arr3=np.eye(10)
print(arr3)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [5]:
arr4=np.eye(4,9)
print(arr4)

[[1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0.]]


In [6]:
arr5=np.diag([5,7,89,1,4,57,21,5,])
print(arr5)

[[ 5  0  0  0  0  0  0  0]
 [ 0  7  0  0  0  0  0  0]
 [ 0  0 89  0  0  0  0  0]
 [ 0  0  0  1  0  0  0  0]
 [ 0  0  0  0  4  0  0  0]
 [ 0  0  0  0  0 57  0  0]
 [ 0  0  0  0  0  0 21  0]
 [ 0  0  0  0  0  0  0  5]]


In [7]:
print(np.diag(arr5))

[ 5  7 89  1  4 57 21  5]


In [8]:
arr6=np.random.randint(0,99,(10))
print(arr6)

[42 92  0 67 10 39 55  6 80 89]


In [9]:
arr7=np.random.rand(5)
print(arr7)

[0.7498556  0.28161411 0.27210596 0.02836376 0.80309197]


In [10]:
arr8=np.random.randn(12)
print(arr8)

[ 0.26959953  0.61779105  0.48882918  1.16023841 -1.19048302 -0.35853376
  0.26694372 -0.85814787 -1.24604609 -1.26970147 -0.63531549 -0.31509848]
