# Stacking

## Stacking in Vector

In [1]:
import numpy as np

In [2]:
arr1=np.arange(0,20)
arr2=np.arange(20,40)
arr3=np.arange(40,60)
arr4=np.arange(60,80)
arr5=np.arange(80,100)

print(arr1,arr2,arr3,arr4,arr5)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19] [20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39] [40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59] [60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79] [80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]


In [3]:
np.hstack((arr1,arr2,arr3,arr4,arr5))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [4]:
np.vstack((arr1,arr2,arr3,arr4,arr5))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
        56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75,
        76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95,
        96, 97, 98, 99]])

## Stacking in Matrix

In [5]:
arr1=np.arange(0,50).reshape(-1,2)
arr2=np.arange(50,100).reshape(-1,2)

In [6]:
np.hstack((arr1,arr2))

array([[ 0,  1, 50, 51],
       [ 2,  3, 52, 53],
       [ 4,  5, 54, 55],
       [ 6,  7, 56, 57],
       [ 8,  9, 58, 59],
       [10, 11, 60, 61],
       [12, 13, 62, 63],
       [14, 15, 64, 65],
       [16, 17, 66, 67],
       [18, 19, 68, 69],
       [20, 21, 70, 71],
       [22, 23, 72, 73],
       [24, 25, 74, 75],
       [26, 27, 76, 77],
       [28, 29, 78, 79],
       [30, 31, 80, 81],
       [32, 33, 82, 83],
       [34, 35, 84, 85],
       [36, 37, 86, 87],
       [38, 39, 88, 89],
       [40, 41, 90, 91],
       [42, 43, 92, 93],
       [44, 45, 94, 95],
       [46, 47, 96, 97],
       [48, 49, 98, 99]])

In [7]:
np.vstack((arr1,arr2))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29],
       [30, 31],
       [32, 33],
       [34, 35],
       [36, 37],
       [38, 39],
       [40, 41],
       [42, 43],
       [44, 45],
       [46, 47],
       [48, 49],
       [50, 51],
       [52, 53],
       [54, 55],
       [56, 57],
       [58, 59],
       [60, 61],
       [62, 63],
       [64, 65],
       [66, 67],
       [68, 69],
       [70, 71],
       [72, 73],
       [74, 75],
       [76, 77],
       [78, 79],
       [80, 81],
       [82, 83],
       [84, 85],
       [86, 87],
       [88, 89],
       [90, 91],
       [92, 93],
       [94, 95],
       [96, 97],
       [98, 99]])