# Some More Functions in Numpy Matrix

In [1]:
import numpy as np

In [2]:
arr1=np.arange(1,101)
arr1

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [3]:
np.random.shuffle(arr1)
arr1

array([ 43,  34,  81,  62,  79,  95,  54,  63,  27,  83,  58,  60,  32,
        31,  61,  68,  37,  50,  93,  82,  19,  48,  24,   5,  39,  46,
        85,  26,  35,  59,  30,  33,   7,  29,  57,  12,  25,  78,  97,
         4,  52,  92,   9,  17,  36,  10,  74,   8,  16,  91,  21,  98,
        15,  40,  66,  51,  99,  77,  72,  14,   6,   2,  65,  69,  47,
        56,  22,  70,  84,  75,  23,  44,  11, 100,   1,  13,  94,  88,
        20,  67,  89,  53,  73,  71,  80,   3,  90,  64,  18,  42,  41,
        76,  96,  38,  86,  49,  55,  87,  28,  45])

In [4]:
arr2=np.random.randint(0,10,100)
arr2

array([8, 9, 1, 7, 6, 9, 9, 2, 4, 6, 5, 1, 4, 2, 9, 2, 8, 4, 5, 9, 9, 9,
       5, 5, 5, 2, 3, 3, 3, 2, 5, 4, 1, 0, 5, 9, 1, 2, 3, 7, 2, 7, 9, 2,
       4, 8, 1, 4, 4, 2, 3, 5, 5, 4, 5, 2, 0, 3, 0, 3, 8, 1, 3, 4, 4, 3,
       4, 8, 2, 8, 6, 5, 9, 4, 3, 8, 4, 2, 0, 9, 4, 1, 9, 3, 4, 5, 2, 4,
       9, 4, 6, 0, 7, 5, 7, 4, 6, 8, 2, 8])

In [5]:
np.unique(arr2)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.unique(arr2).size

10

In [7]:
np.unique(arr2,return_index=True)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([33,  2,  7, 26,  8, 10,  4,  3,  0,  1], dtype=int64))

In [8]:
np.unique(arr2,return_index=True,return_counts=True)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([33,  2,  7, 26,  8, 10,  4,  3,  0,  1], dtype=int64),
 array([ 5,  7, 14, 11, 18, 13,  5,  5,  9, 13], dtype=int64))