In [1]:
import numpy as np

In [2]:
arr1=np.arange(10)+1
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
arr2=arr1[1:6]
arr2

array([2, 3, 4, 5, 6])

In [4]:
arr2[:]=0
arr1

array([ 1,  0,  0,  0,  0,  0,  7,  8,  9, 10])

# Now slicing with .copy() function

In [5]:
arr3=np.arange(10)+1
arr3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
arr4=arr3[1:6].copy()
arr4

array([2, 3, 4, 5, 6])

In [7]:
arr4[:]=0
arr3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])