In [1]:
import numpy as np

In [2]:
arr1=np.arange(100)+1
arr1=arr1.reshape(10,10)
arr1

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [3]:
arr1[6:8,3:8]

array([[64, 65, 66, 67, 68],
       [74, 75, 76, 77, 78]])

In [4]:
arr1[5:,:2]

array([[51, 52],
       [61, 62],
       [71, 72],
       [81, 82],
       [91, 92]])

In [5]:
arr1[:-2,7:]

array([[ 8,  9, 10],
       [18, 19, 20],
       [28, 29, 30],
       [38, 39, 40],
       [48, 49, 50],
       [58, 59, 60],
       [68, 69, 70],
       [78, 79, 80]])

In [6]:
arr1[:-4,-3:]

array([[ 8,  9, 10],
       [18, 19, 20],
       [28, 29, 30],
       [38, 39, 40],
       [48, 49, 50],
       [58, 59, 60]])

In [7]:
arr1[-3:-2,-5:-2]

array([[76, 77, 78]])