# Conditional Selection

In [1]:
import numpy as np

In [2]:
arr1=np.random.randint(0,99,100)
arr1

array([75, 14, 97, 89, 58,  0, 19, 71,  6, 55, 25,  9, 95, 81,  1, 39, 42,
       54, 71, 55, 19, 52,  4, 91,  9, 63, 40, 88, 76, 48, 96, 10, 41, 25,
       43,  6, 83, 52, 60, 90, 48, 46, 70, 98, 95, 12, 32,  4, 18,  4, 29,
       52, 21, 86, 75, 33, 62,  8, 31, 56, 78, 49, 33, 18, 35, 85, 10, 44,
       66,  5, 52, 55, 40, 49, 82, 58, 71, 48, 56, 27, 40, 41, 56, 81, 10,
       23, 70, 59, 54, 35, 59,  0, 63, 60, 55, 58, 78, 89, 87, 95])

In [3]:
arr1>60

array([ True, False,  True,  True, False, False, False,  True, False,
       False, False, False,  True,  True, False, False, False, False,
        True, False, False, False, False,  True, False,  True, False,
        True,  True, False,  True, False, False, False, False, False,
        True, False, False,  True, False, False,  True,  True,  True,
       False, False, False, False, False, False, False, False,  True,
        True, False,  True, False, False, False,  True, False, False,
       False, False,  True, False, False,  True, False, False, False,
       False, False,  True, False,  True, False, False, False, False,
       False, False,  True, False, False,  True, False, False, False,
       False, False,  True, False, False, False,  True,  True,  True,
        True])

In [4]:
arr1[arr1>90]

array([97, 95, 91, 96, 98, 95, 95])

In [5]:
arr1[arr1%7==0]

array([14,  0, 42, 91, 63, 70, 98, 21, 56, 49, 35, 49, 56, 56, 70, 35,  0,
       63])

In [6]:
arr1[arr1%11==1]

array([89,  1, 12, 56, 78, 56, 56, 23, 78, 89])

In [7]:
arr1[arr1<50]*=2
arr1

array([75, 28, 97, 89, 58,  0, 38, 71, 12, 55, 50, 18, 95, 81,  2, 78, 84,
       54, 71, 55, 38, 52,  8, 91, 18, 63, 80, 88, 76, 96, 96, 20, 82, 50,
       86, 12, 83, 52, 60, 90, 96, 92, 70, 98, 95, 24, 64,  8, 36,  8, 58,
       52, 42, 86, 75, 66, 62, 16, 62, 56, 78, 98, 66, 36, 70, 85, 20, 88,
       66, 10, 52, 55, 80, 98, 82, 58, 71, 96, 56, 54, 80, 82, 56, 81, 20,
       46, 70, 59, 54, 70, 59,  0, 63, 60, 55, 58, 78, 89, 87, 95])