# Functions in Numpy Matrix

In [1]:
import numpy as np

In [2]:
arr1=np.random.randint(100,999,(5,5))
arr1

array([[100, 954, 642, 255, 565],
       [853, 780, 154, 527, 405],
       [652, 373, 168, 692, 379],
       [638, 641, 887, 387, 124],
       [686, 792, 885, 138, 217]])

In [3]:
np.sum(arr1)

12894

In [4]:
arr1.sum()

12894

In [5]:
np.min(arr1)

100

In [6]:
np.min(arr1)

100

In [7]:
np.max(arr1)

954

In [8]:
np.argmin(arr1)

0

In [9]:
np.argmax(arr1)

1

In [10]:
np.sqrt(arr1)

array([[10.        , 30.88689042, 25.33771892, 15.96871942, 23.76972865],
       [29.20616373, 27.92848009, 12.40967365, 22.95648057, 20.1246118 ],
       [25.53429067, 19.31320792, 12.9614814 , 26.30589288, 19.46792233],
       [25.25866188, 25.3179778 , 29.78254522, 19.67231557, 11.13552873],
       [26.19160171, 28.14249456, 29.74894956, 11.74734012, 14.73091986]])

In [11]:
np.sin(arr1)

array([[-0.50636564, -0.864506  ,  0.89795421, -0.50639163, -0.46769187],
       [-0.99834189,  0.77392886, -0.06192034, -0.70863787,  0.26234577],
       [-0.99286546,  0.75096734, -0.99717329,  0.75102706,  0.90556557],
       [-0.25388168,  0.1148447 ,  0.87761869, -0.55145183, -0.99568699],
       [ 0.90560393,  0.31328604, -0.80109851, -0.22805226, -0.22808161]])

In [12]:
np.cos(arr1)

array([[ 0.86231887,  0.5026225 ,  0.44008889, -0.86230361,  0.88389157],
       [ 0.05756271,  0.63327255, -0.99808109,  0.70557237, -0.96497394],
       [ 0.11923999, -0.66033935, -0.07513609,  0.66027143, -0.42420631],
       [-0.96723528,  0.99338346,  0.4793594 , -0.83420674, -0.0927762 ],
       [ 0.42412441,  0.94965881,  0.59853252,  0.97364889, -0.97364202]])

In [13]:
np.linspace(1,99,25).reshape(5,5)

array([[ 1.        ,  5.08333333,  9.16666667, 13.25      , 17.33333333],
       [21.41666667, 25.5       , 29.58333333, 33.66666667, 37.75      ],
       [41.83333333, 45.91666667, 50.        , 54.08333333, 58.16666667],
       [62.25      , 66.33333333, 70.41666667, 74.5       , 78.58333333],
       [82.66666667, 86.75      , 90.83333333, 94.91666667, 99.        ]])

# Some Extra Ordinary Functions in Numpy

In [14]:
arr1

array([[100, 954, 642, 255, 565],
       [853, 780, 154, 527, 405],
       [652, 373, 168, 692, 379],
       [638, 641, 887, 387, 124],
       [686, 792, 885, 138, 217]])

In [15]:
np.sum(arr1,axis=1)

array([2516, 2719, 2264, 2677, 2718])

In [16]:
np.max(arr1,axis=1)

array([954, 853, 692, 887, 885])

In [17]:
np.argmax(arr1,axis=1)

array([1, 0, 3, 2, 2], dtype=int64)

In [18]:
np.min(arr1,axis=1)

array([100, 154, 168, 124, 138])

In [19]:
np.argmin(arr1,axis=1)

array([0, 2, 2, 4, 3], dtype=int64)

In [20]:
np.cumsum(arr1)

array([  100,  1054,  1696,  1951,  2516,  3369,  4149,  4303,  4830,
        5235,  5887,  6260,  6428,  7120,  7499,  8137,  8778,  9665,
       10052, 10176, 10862, 11654, 12539, 12677, 12894], dtype=int32)

In [21]:
np.cumsum(arr1,axis=1)

array([[ 100, 1054, 1696, 1951, 2516],
       [ 853, 1633, 1787, 2314, 2719],
       [ 652, 1025, 1193, 1885, 2264],
       [ 638, 1279, 2166, 2553, 2677],
       [ 686, 1478, 2363, 2501, 2718]], dtype=int32)