# Functions in Numpy

In [1]:
import numpy as np

In [2]:
arr1=np.random.randint(100,999,20)
arr1

array([896, 689, 327, 565, 412, 104, 527, 940, 226, 621, 799, 842, 946,
       876, 740, 448, 695, 788, 229, 416])

In [3]:
np.min(arr1)

104

In [4]:
np.min(arr1)

104

In [5]:
np.max(arr1)

946

In [6]:
np.argmin(arr1)

5

In [7]:
np.argmax(arr1)

12

In [8]:
np.sqrt(arr1)

array([29.93325909, 26.2488095 , 18.08314132, 23.76972865, 20.29778313,
       10.19803903, 22.95648057, 30.65941943, 15.03329638, 24.91987159,
       28.26658805, 29.01723626, 30.757113  , 29.59729717, 27.20294102,
       21.16601049, 26.36285265, 28.0713377 , 15.13274595, 20.39607805])

In [9]:
np.sin(arr1)

array([-0.60207208, -0.83668866,  0.27093481, -0.46769187, -0.43619188,
       -0.3216224 , -0.70863787, -0.61611169, -0.19344382, -0.86003865,
        0.86010016,  0.05314379, -0.37148806,  0.48323878, -0.98802232,
        0.94827257, -0.65033364,  0.51392674,  0.32996237,  0.96612555])

In [10]:
np.cos(arr1)

array([-0.79844174, -0.54767882,  0.9625977 ,  0.88389157, -0.89985368,
       -0.94686801,  0.70557237, -0.7876588 ,  0.98111135,  0.5102289 ,
        0.51012519,  0.99858687, -0.92843773, -0.87548859,  0.15431102,
       -0.31745729, -0.75964871, -0.85783408, -0.94399409,  0.25807251])

In [15]:
np.linspace(1,99,101)

array([ 1.  ,  1.98,  2.96,  3.94,  4.92,  5.9 ,  6.88,  7.86,  8.84,
        9.82, 10.8 , 11.78, 12.76, 13.74, 14.72, 15.7 , 16.68, 17.66,
       18.64, 19.62, 20.6 , 21.58, 22.56, 23.54, 24.52, 25.5 , 26.48,
       27.46, 28.44, 29.42, 30.4 , 31.38, 32.36, 33.34, 34.32, 35.3 ,
       36.28, 37.26, 38.24, 39.22, 40.2 , 41.18, 42.16, 43.14, 44.12,
       45.1 , 46.08, 47.06, 48.04, 49.02, 50.  , 50.98, 51.96, 52.94,
       53.92, 54.9 , 55.88, 56.86, 57.84, 58.82, 59.8 , 60.78, 61.76,
       62.74, 63.72, 64.7 , 65.68, 66.66, 67.64, 68.62, 69.6 , 70.58,
       71.56, 72.54, 73.52, 74.5 , 75.48, 76.46, 77.44, 78.42, 79.4 ,
       80.38, 81.36, 82.34, 83.32, 84.3 , 85.28, 86.26, 87.24, 88.22,
       89.2 , 90.18, 91.16, 92.14, 93.12, 94.1 , 95.08, 96.06, 97.04,
       98.02, 99.  ])