In [1]:
import numpy as np

In [2]:
np.random.seed(12)
arr1=np.random.randint(1,100,10)
print(arr1)

[76 28  7  3  4 68 77 49 23 50]


In [3]:
np.random.seed(12)
arr2=np.random.randint(1,100,10)
print(arr2)

[76 28  7  3  4 68 77 49 23 50]


In [4]:
np.random.seed(0)
arr3=np.random.randint(1,100,10)
print(arr3)

[45 48 65 68 68 10 84 22 37 88]
